### ISSUE TITLE
magit-status fails to start with some packages not found error message.

### ISSUE THREAD

**Issue by c02y** [magit/magit-filenotify#5]
After I update some packages in `package.el`, I try to magit-status, error message will show in minibuffer/**Message** buffer, like(and **magit...** buffer is empty):
    
    file-notify-add-watch: File does not exist: no such file or directory, /home/chz/.emacs.d/elpa/package-name...

Actually, `package-name...` is right in `~/.emacs.d/elpa/` directory, and I already have `(package-initialize)` at the beginning of my `~/.emacs` file.

But if I disable/comment-out `magit-filenotify-mode`, `magit-status` command will be fine, there is no error message.

**Comment by c02y** [comment]
> Which file-notification backend are you using? See the value of `file-notify--library`. 
    Its value is gfilenotify

> Does it happen when you call magit-status on that git repo for the first time or only for the second time?
    Every time with the same err message.

> What happens if you run (file-exists-p "/home/chz/.emacs.d/elpa/package-name...")?
The version of the `package-name` in the error message is previous version before I updated it using the `package`, if I get that version(v1) back, it will show an error message about `the previous version of another package` before I updated it using `package`:
    file-notify-add-watch: File does not exist: no such file or directory, /home/chz/.emacs.d/elpa/another-package-name...

**Comment by caleb** [comment]
I'm seeing this as well. My `file-notify--library` is `gfilenotify` as well.

The full error is:

```
file-notify-add-watch: File does not exist: no such file or directory, /Users/caleb/Projects/snell_luxury_rentals/"db/development-photos/esp\303\255ritu-del-mar
```

I would guess that maybe the unicode in the directory name is tripping it up, the name is:

```
espíritu-del-mar
```

(Notice the `í` character)

I haven't debugged this at all since I just started seeing it, but I thought it might help someone who knows more about this than I do. I am on OS X 10.10, Running Emacs 24.4.1 and magit-20150116.517.

Let me know if there's anything i can do to help debug this.
