### ISSUE TITLE
Should we deprecate this package?

### ISSUE THREAD

**Issue by tarsius** [magit/magit-filenotify#8]
@ruediger In order to fix #5, I've had another look, the first in a long time, and I must say I don't think this package really is a good idea, and also have some doubts it actually does what it is intended to do. Here are some issues I found:

1. Only directories are being watched. Unless I misunderstand how `file-notify-add-watch` works that means that the status buffer is only ever refreshed by this package if a file is created or deleted.
2. Files (as per (1) probably only directories) are only being watched if the exist at the time the mode is turned on.
3. If (1) is fixed and the package starts to behave as intended, then it gets worse. When doing something in Magit, or outside of its control, changes many files in the repository, then the status buffer gets refreshed once for each file that had an event. Again of course assuming I don't misunderstand how this works.

Finally, even if these things are fixed, I don't think users have much to gain from using this package. Performing any action in Magit causes the status buffer to be refreshed anyway. When doing work outside of Magit, on the command line or by editing and saving a file (in Emacs), then that buffer is not refreshed, but that can be done simply by pressing `g`.

It seems it would be more useful if saving a file in Emacs would optionally trigger a refresh, and if we just accepted that after external changes the user has to refresh explicitly.

I am considering removing this package from the organization account, but would like to first hear your thoughts on this.

**Comment by ruediger** [comment]
>  Unless I misunderstand how file-notify-add-watch works that means that the status buffer is only ever refreshed by this package if a file is created or deleted.

You misunderstood. It is also refreshed when a file is changed.

> Files (as per (1) probably only directories) are only being watched if the exist at the time the mode is turned on.

This should only be a problem for new directories. But it can be fixed. I have to test it first though.

> If (1) is fixed and the package starts to behave as intended, then it gets worse. When doing something in Magit, or outside of its control, changes many files in the repository, then the status buffer gets refreshed once for each file that had an event. Again of course assuming I don't misunderstand how this works.

Yes, that can be a problem. I never experienced it though. But we added the ignore list to prevent at least the lock/backup files from triggering it. We could add a timeout though and only refresh, e.g., only once per second max. But it seems nobody has complained about that so far.

> Finally, even if these things are fixed, I don't think users have much to gain from using this package.

I think it actually solves a problem and it seems to have gained some usage. I don't see a reason why it should be removed.

**Comment by tarsius** [comment]
> You misunderstood. It is also refreshed when a file is changed.

Could you please elaborate on that a bit? All `file-notify-add-watch` has to say on the matter is

> If FILE is a directory, 'change' watches for file creation or deletion in that directory.  This does not work recursively.

Which doesn't sound like it also watches events for files in that directory.

> I think it actually solves a problem and it seems to have gained some usage. I don't see a reason why it should be removed.

Well, (3) is a quite serious issue. You have to do something about that, then it can stay. But...

> We could add a timeout though and only refresh, e.g., only once per second max

...sounds like a major hack. Once you do that, we are back to having to press `g` to really be sure. So what problem exactly does this package solve?

**Comment by PythonNut** [comment]
I, personally, love the idea behind this package. 

I hate buffers I have to refresh because I can never trust them. Even when I refresh with <kbd>g</kbd>, as the buffer gets more stale, my confidence in the accuracy of its contents dwindles. 

`magit-filenotify` seems to fix this. I can always trust that it's up-to-date... except when it's not (which is exceedingly rare). 

> > We could add a timeout though and only refresh, e.g., only once per second max

> ...sounds like a major hack. 

Actually, buffering the requests seems like a great idea. I actually wrote a similar [vcs system](https://github.com/PythonNut/zsh-config) that uses this exact approach for great good. I've been using it in production for a long time and it seems pretty bulletproof.

> Once you do that, we are back to having to press g to really be sure.

Only if you're so impatient that 1s delay is too long. On my computer the lag is greater than that anyway. 


> If (1) is fixed and the package starts to behave as intended, then it gets worse. When doing something in Magit, or outside of its control, changes many files in the repository, then the status buffer gets refreshed once for each file that had an event. Again of course assuming I don't misunderstand how this works.

I _have_ noticed that this is an issue. Whenever I touch my tree, Emacs slows down considerably, even if the magit buffers aren't visible. If I kill them, the lag goes away. My case is probably worse than most. I run Emacs on a Raspberry Pi with pathetic I/O and an old laptop with a slow magnetic hard drive.

In particular, you do need to blacklist some of the files in the `.git` directories, as you can easily run into a feedback loop where simply checking the status modifies the filesystem tree, which then causes another check... ad infinitum. I got around this in my system by blacklisting the `index.lock`, which seems to fix the issue.

**Comment by tarsius** [comment]
in case there is some doubts about that, I don't *want* to deprecate this, I was just *wondering* whether it should be. So thanks for the feedback. (And if you have more, keep it coming. But I am closing this, because we have arrived at an answer, *no*).
